spring:
  datasource:

    url: jdbc:mysql://121.5.154.71:3306/HanGouT?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: rootHGT@5

server:
  port:
